stages:
  - build
  - publish

build-binaries:
  stage: build
  parallel:
    matrix:
      - IMAGE: node:lts-bullseye
        TARGET: x86_64-unknown-linux-gnu
        PLATFORM: linux-x64-gnu
      - IMAGE: node:lts-alpine
        TARGET: x86_64-unknown-linux-musl
        PLATFORM: linux-x64-musl
  image: $IMAGE
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
      - .cargo/
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
    - source "$HOME/.cargo/env"
    - npm ci --cache .npm --prefer-offline
    - npm run build -- --target $TARGET
    - mv @suvayu/converter.$PLATFORM.node npm/$PLATFORM/
  artifacts:
    paths:
      - npm/$PLATFORM

publish:
  stage: publish
  image: node:lts-bullseye
  needs:
    - job: "build-binaries [node:lts-bullseye x86_64-unknown-linux-gnu linux-x64-gnu]"
      artifacts: true
    - job: "build-binaries [node:lts-alpine x86_64-unknown-linux-musl linux-x64-musl]"
      artifacts: true
  rules:
    - if: $CI_GIT_COMMIT_TAG
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" >> ~/.npmrc
    - |
      for p in linux-x64-{gnu,musl}; do
          pushd npm/$p && {
                npm publish --tag testing --access public
                popd
            }
      done
    - npm publish --tag testing --access public
